
-- DESCRIÇÃO DOS COMANDOS SQL PARA CRIAÇÃO DO BANCO DE DADOS DA APLICAÇÃO:

-- CRIAÇÃO DAS TABELAS:

CREATE TABLE MATEMATICA (
    IDQUESTAO INTEGER PRIMARY KEY,
    ENUNCIADO TEXT NOT NULL,
    ALTERNATIVA_A TEXT NOT NULL,
    ALTERNATIVA_B TEXT NOT NULL,
    ALTERNATIVA_C TEXT NOT NULL,
    ALTERNATIVA_D TEXT NOT NULL,
    ALTERNATIVA_E TEXT NOT NULL,
    RESPOSTA CHAR(1)
);

INSERT INTO "TEMA" VALUES (IDQUESTAO, ENUNCIADO, ALTERNATIVA_A, ALTERNATIVA_B, ALTERNATIVA_C
ALTERNATIVA_D, ALTERNATIVA_E, RESPOSTA, ID_TEMA)

CREATE TABLE FISICA (
    IDQUESTAO INTEGER PRIMARY KEY,
    ENUNCIADO TEXT NOT NULL,
    ALTERNATIVA_A TEXT NOT NULL,
    ALTERNATIVA_B TEXT NOT NULL,
    ALTERNATIVA_C TEXT NOT NULL,
    ALTERNATIVA_D TEXT NOT NULL,
    ALTERNATIVA_E TEXT NOT NULL,
    RESPOSTA CHAR(1)
);


CREATE TABLE QUIMICA (
    IDQUESTAO INTEGER PRIMARY KEY,
    ENUNCIADO TEXT NOT NULL,
    ALTERNATIVA_A TEXT NOT NULL,
    ALTERNATIVA_B TEXT NOT NULL,
    ALTERNATIVA_C TEXT NOT NULL,
    ALTERNATIVA_D TEXT NOT NULL,
    ALTERNATIVA_E TEXT NOT NULL,
    RESPOSTA CHAR(1)
);

CREATE TABLE BIOLOGIA (
    IDQUESTAO INTEGER PRIMARY KEY,
    ENUNCIADO TEXT NOT NULL,
    ALTERNATIVA_A TEXT NOT NULL,
    ALTERNATIVA_B TEXT NOT NULL,
    ALTERNATIVA_C TEXT NOT NULL,
    ALTERNATIVA_D TEXT NOT NULL,
    ALTERNATIVA_E TEXT NOT NULL,
    RESPOSTA CHAR(1)
);

CREATE TABLE HISTORIA (
    IDQUESTAO INTEGER PRIMARY KEY,
    ENUNCIADO TEXT NOT NULL,
    ALTERNATIVA_A TEXT NOT NULL,
    ALTERNATIVA_B TEXT NOT NULL,
    ALTERNATIVA_C TEXT NOT NULL,
    ALTERNATIVA_D TEXT NOT NULL,
    ALTERNATIVA_E TEXT NOT NULL,
    RESPOSTA CHAR(1)
);

CREATE TABLE GEOGRAFIA (
    IDQUESTAO INTEGER PRIMARY KEY,
    ENUNCIADO TEXT NOT NULL,
    ALTERNATIVA_A TEXT NOT NULL,
    ALTERNATIVA_B TEXT NOT NULL,
    ALTERNATIVA_C TEXT NOT NULL,
    ALTERNATIVA_D TEXT NOT NULL,
    ALTERNATIVA_E TEXT NOT NULL,
    RESPOSTA CHAR(1)
);

CREATE TABLE FILOSOFIA (
    IDQUESTAO INTEGER PRIMARY KEY,
    ENUNCIADO TEXT NOT NULL,
    ALTERNATIVA_A TEXT NOT NULL,
    ALTERNATIVA_B TEXT NOT NULL,
    ALTERNATIVA_C TEXT NOT NULL,
    ALTERNATIVA_D TEXT NOT NULL,
    ALTERNATIVA_E TEXT NOT NULL,
    RESPOSTA CHAR(1)
);

CREATE TABLE SOCIOLOGIA (
    IDQUESTAO INTEGER PRIMARY KEY,
    ENUNCIADO TEXT NOT NULL,
    ALTERNATIVA_A TEXT NOT NULL,
    ALTERNATIVA_B TEXT NOT NULL,
    ALTERNATIVA_C TEXT NOT NULL,
    ALTERNATIVA_D TEXT NOT NULL,
    ALTERNATIVA_E TEXT NOT NULL,
    RESPOSTA CHAR(1)
);

CREATE TABLE PORTUGUES (
    IDQUESTAO INTEGER PRIMARY KEY,
    ENUNCIADO TEXT NOT NULL,
    ALTERNATIVA_A TEXT NOT NULL,
    ALTERNATIVA_B TEXT NOT NULL,
    ALTERNATIVA_C TEXT NOT NULL,
    ALTERNATIVA_D TEXT NOT NULL,
    ALTERNATIVA_E TEXT NOT NULL,
    RESPOSTA CHAR(1)
);

CREATE TABLE CONTADOR (
    IDCONTADOR INTEGER PRIMARY KEY,
    CONTADOR_MATEMATICA INT,
    CONTADOR_FISICA INT,
    CONTADOR_QUIMICA INT,
    CONTADOR_BIOLOGIA INT,
    CONTADOR_HISTORIA INT,
    CONTADOR_GEOGRAFIA INT,
    CONTADOR_FILOSOFIA INT,
    CONTADOR_SOCIOLOGIA INT,
    CONTADOR_PORTUGUES INT
);

CREATE TABLE TEMA (
    IDTEMA INTEGER PRIMARY KEY,
    TEMA VARCHAR
);

INSERT INTO TEMA VALUES (1, "Matemática");
INSERT INTO TEMA VALUES (2, "Física");
INSERT INTO TEMA VALUES (3, "Química");
INSERT INTO TEMA VALUES (4, "Biologia");
INSERT INTO TEMA VALUES (5, "História");
INSERT INTO TEMA VALUES (6, "Geografia");
INSERT INTO TEMA VALUES (7, "Filosofia");
INSERT INTO TEMA VALUES (8, "Sociologia");
INSERT INTO TEMA VALUES (9, "Português");

ALTER TABLE MATEMATICA ADD COLUMN ID_TEMA INTERGER REFERENCES TEMA(IDTEMA);
ALTER TABLE FISICA ADD COLUMN ID_TEMA INTERGER REFERENCES TEMA(IDTEMA);
ALTER TABLE QUIMICA ADD COLUMN ID_TEMA INTERGER REFERENCES TEMA(IDTEMA);
ALTER TABLE BIOLOGIA ADD COLUMN ID_TEMA INTERGER REFERENCES TEMA(IDTEMA);
ALTER TABLE HISTORIA ADD COLUMN ID_TEMA INTERGER REFERENCES TEMA(IDTEMA);
ALTER TABLE GEOGRAFIA ADD COLUMN ID_TEMA INTERGER REFERENCES TEMA(IDTEMA);
ALTER TABLE FILOSOFIA ADD COLUMN ID_TEMA INTERGER REFERENCES TEMA(IDTEMA);
ALTER TABLE SOCIOLOGIA ADD COLUMN ID_TEMA INTERGER REFERENCES TEMA(IDTEMA);
ALTER TABLE PORTUGUES ADD COLUMN ID_TEMA INTERGER REFERENCES TEMA(IDTEMA);

UPDATE MATEMATICA
SET ID_TEMA = 1 WHERE IDQUESTAO = 2;
UPDATE FISICA
SET ID_TEMA = 2 WHERE IDQUESTAO = 1;
UPDATE FISICA
SET ID_TEMA = 2 WHERE IDQUESTAO = 2;
UPDATE QUIMICA
SET ID_TEMA = 3 WHERE IDQUESTAO = 1;
UPDATE BIOLOGIA
SET ID_TEMA = 4 WHERE IDQUESTAO = 1;
UPDATE HISTORIA
SET ID_TEMA = 5 WHERE IDQUESTAO = 1;
UPDATE GEOGRAFIA
SET ID_TEMA = 6 WHERE IDQUESTAO = 1;
UPDATE FILOSOFIA
SET ID_TEMA = 7 WHERE IDQUESTAO = 1;
UPDATE SOCIOLOGIA
SET ID_TEMA = 8 WHERE IDQUESTAO = 1;
UPDATE PORTUGUES
SET ID_TEMA = 9 WHERE IDQUESTAO = 1;

-- TRIGGERS++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++===

CREATE TRIGGER UPT_MAT_COUNT AFTER INSERT ON MATEMATICA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_MATEMATICA = CONTADOR_MATEMATICA + 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER UPT_FIS_COUNT AFTER INSERT ON FISICA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_FISICA = CONTADOR_FISICA + 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER UPT_QUIM_COUNT AFTER INSERT ON QUIMICA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_QUIMICA = CONTADOR_QUIMICA + 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER UPT_BIO_COUNT AFTER INSERT ON BIOLOGIA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_BIOLOGIA = CONTADOR_BIOLOGIA + 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER UPT_HIST_COUNT AFTER INSERT ON HISTORIA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_HISTORIA = CONTADOR_HISTORIA + 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER UPT_GEO_COUNT AFTER INSERT ON GEOGRAFIA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_GEOGRAFIA = CONTADOR_GEOGRAFIA + 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER UPT_FILO_COUNT AFTER INSERT ON FILOSOFIA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_FILOSOFIA = CONTADOR_FILOSOFIA + 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER UPT_SOCIO_COUNT AFTER INSERT ON SOCIOLOGIA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_SOCIOLOGIA = CONTADOR_SOCIOLOGIA + 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER UPT_PORT_COUNT AFTER INSERT ON PORTUGUES
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_PORTUGUES = CONTADOR_PORTUGUES + 1
    WHERE IDCONTADOR = 1;
END;

-- ======================================================================================================================

CREATE TRIGGER DEL_MATH_COUNT AFTER DELETE ON MATEMATICA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_MATEMATICA = CONTADOR_MATEMATICA - 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER DEL_FIS_COUNT AFTER DELETE ON FISICA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_FISICA = CONTADOR_FISICA - 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER DEL_QUIM_COUNT AFTER DELETE ON QUIMICA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_QUIMICA = CONTADOR_QUIMICA - 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER DEL_BIO_COUNT AFTER DELETE ON BIOLOGIA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_BIOLOGIA = CONTADOR_BIOLOGIA - 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER DEL_HIST_COUNT AFTER DELETE ON HISTORIA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_HISTORIA = CONTADOR_HISTORIA - 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER DEL_GEO_COUNT AFTER DELETE ON GEOGRAFIA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_GEOGRAFIA = CONTADOR_GEOGRAFIA - 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER DEL_FILO_COUNT AFTER DELETE ON FILOSOFIA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_FILOSOFIA = CONTADOR_FILOSOFIA - 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER DEL_SOCIO_COUNT AFTER DELETE ON SOCIOLOGIA
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_SOCIOLOGIA = CONTADOR_SOCIOLOGIA - 1
    WHERE IDCONTADOR = 1;
END;

CREATE TRIGGER DEL_PORT_COUNT AFTER DELETE ON PORTUGUES
BEGIN

    UPDATE CONTADOR
    SET CONTADOR_PORTUGUES = CONTADOR_PORTUGUES - 1
    WHERE IDCONTADOR = 1;
END;
